name: attendance_app
<<<<<<< HEAD
description: "A new Flutter project."
=======
description: "Hris Attendance App integrate with Go cv HRIS"
>>>>>>> master
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
<<<<<<< HEAD
=======
  awesome_dialog: ^3.2.1
>>>>>>> master
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dart_amqp: ^0.3.1
  dio: ^5.7.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  meta: ^1.15.0
  path: ^1.9.0
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.1
<<<<<<< HEAD
=======
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  json_annotation: 
  lottie: 
  chucker_flutter: 
  easy_date_timeline: 
  slide_to_act: 
  animated_bottom_navigation_bar: 
>>>>>>> master

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
<<<<<<< HEAD

  syncfusion_flutter_datepicker: ^28.1.36
=======
  json_serializable: ^6.11.2
  build_runner: ^2.4.6

  
>>>>>>> master

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
